apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    monitoring: monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 5i
  accessModes:
    - ReadWriteOnce

