apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  config:
    publicUrl: http://minio.velero.svc.cluster.local:9000
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.velero.svc.cluster.local:9000
  objectStorage:
    bucket: velero
  provider: aws