apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: velero
type: kubernetes.io/basic-auth
stringData:
  username: minio
  password: minio123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: velero
  labels:
    component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      component: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        imagePullPolicy: IfNotPresent
        args:
          - server
          - /data
          - --config-dir=/config
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: credentials
                key: username
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: password
        ports:
          - containerPort: 9000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /data
            name: data
          - mountPath: /config
            name: config
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  until nc -z localhost 9000; do "Waiting for MinIO..."; sleep 2; done;
                  mc alias set local http://localhost:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
                  mc mb local/velero 2>/dev/null || true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pv-claim
        - name: config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: velero
  labels:
    component: minio
spec:
  selector:
    component: minio
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  type: ClusterIP